### ISSUE TITLE
Shadow has to be applied on body when choosing the date

### ISSUE THREAD

**Issue by lonk** [buckless/datetime-picker#3]
It works on the time chooser

![capture d ecran de 2017-05-23 16-29-17](https://cloud.githubusercontent.com/assets/2729398/26359915/fd37b2dc-3fd6-11e7-9fe2-0219f5011f52.png)

**Comment by gjuchault** [comment]
Fixed by 149b75abbb882c3d031369cd24128f5484ad5070
